INSERT INTO WINE (ID, NAME, WINERY, VARIETAL, TYPE, APPELLATION, VINTAGE, PRICE, CREATEDDATE, LASTMODIFIEDDATE)
    VALUES (1, 'Boulder Bluff Pinot Noir', 'Adelsheim', 'Pinot Noir', 'RED', 'Willamette Valley', 2008, 68.00, NOW(), NOW());

INSERT INTO USER (ID, USERNAME, CREATEDDATE, LASTMODIFIEDDATE)
    VALUES (1, 'John Doe', NOW(), NOW());

INSERT INTO WINE_RATING (ID, SCORE, REVIEW, WINEID, USERID, CREATEDDATE, LASTMODIFIEDDATE)
    VALUES (1, 5, 'Terrific!', 1, 1, NOW(), NOW());
